"""Portable review workspace: source-linked comparisons, refresh history, explicit unknowns."""
import argparse
import json
from pathlib import Path

TEMPLATE = '''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Signalpost Evidence | Company review</title><style>
:root{--ink:#182f3a;--muted:#577078;--line:#ccdcd9;--green:#16614f;--pale:#eef4f1;--amber:#855022}*{box-sizing:border-box}
body{margin:0;background:#f5f7f4;color:var(--ink);font:15px/1.55 system-ui,sans-serif}header{background:#143e37;color:#f5faf5;padding:32px max(24px,calc((100vw - 1240px)/2));border-bottom:5px solid #b9ce80}
header .eyebrow{font-size:12px;text-transform:uppercase;letter-spacing:.16em;color:#c4d8b2}h1{font-size:36px;font-weight:550;letter-spacing:-.035em;margin:8px 0}header p{max-width:750px;color:#dce8de;margin:4px 0}
main{max-width:1288px;margin:auto;padding:24px}h2{font-size:23px;line-height:1.3;letter-spacing:-.02em;margin:0 0 8px}h3{font-size:17px;margin:0 0 8px}small,.muted{color:var(--muted)}a{color:#0d6555;overflow-wrap:anywhere}button,select,input{font:inherit;border:1px solid #a8beb8;border-radius:6px;background:white;color:var(--ink);padding:10px 13px}button{cursor:pointer}button:hover{background:#e5eee7}button:disabled{opacity:.45;cursor:default}button.primary{background:var(--green);color:white}button:focus-visible,select:focus-visible,input:focus-visible,summary:focus-visible,a:focus-visible{outline:3px solid #a58622;outline-offset:3px}
.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:22px}.stat{background:white;border:1px solid var(--line);padding:17px;border-radius:8px}.stat b{display:block;font-size:26px;font-weight:550}.stat span{font-size:12px;color:var(--muted)}.toolbar{display:flex;flex-wrap:wrap;align-items:end;gap:12px;margin-bottom:18px}.toolbar label{display:block;font-size:12px;margin-bottom:5px}.search{flex:1;min-width:240px}.search input{width:100%}.rowhead{display:flex;justify-content:space-between;align-items:center;gap:12px}.rowhead label{font-size:12px;white-space:nowrap}.pill{font-size:11px;padding:3px 9px;border-radius:20px;background:var(--pale);color:var(--green);display:inline-block;margin-right:5px}.warning{background:#fbf1df;color:var(--amber)}
article,.panel{background:white;border:1px solid var(--line);border-radius:9px;margin:14px 0;padding:22px}.metrics{display:flex;gap:28px;flex-wrap:wrap;border-block:1px solid #e1e9e3;margin:18px 0;padding:12px 0}.metrics span{font-size:12px;color:var(--muted)}.metrics b{display:block;font-size:16px;font-weight:550;color:var(--ink)}.summarytext{max-width:950px}.insight{margin:12px 0}.insight p{margin:3px 0}.refs{font-size:11px}.refs a{margin-right:12px}.limit{border-left:3px solid #d7bb7d;padding:5px 14px;background:#fffbf2;font-size:13px;margin:8px 0}.calc{border-left:3px solid #75a192;padding-left:14px}details{border-top:1px solid #e1e9e3;margin-top:15px;padding-top:8px}summary{cursor:pointer;font-weight:550;padding:7px 0}table{width:100%;border-collapse:collapse;font-size:13px}td,th{padding:12px 10px;border-bottom:1px solid #dde6e0;vertical-align:top;text-align:left}th{background:#f2f6f1;font-weight:550}td{overflow-wrap:anywhere}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:12px/1.6 ui-monospace,monospace;margin:4px 0}.unknown{color:var(--amber)}.available{color:var(--green)}.scroll{overflow:auto}.comparetable{min-width:630px}.comparetable td{min-width:165px;max-width:330px}.facts td:nth-child(2){max-width:450px}.facts td:nth-child(3){max-width:340px}.source{font-size:12px;border-left:2px solid #b9d4c5;padding-left:9px;margin:8px 0}.source small{display:block;font-size:10px}.change{border-left:3px solid #809e71;margin:12px 0;padding-left:13px}.changegrid{display:grid;grid-template-columns:1fr 1fr;gap:15px}.empty{text-align:center;padding:40px;color:var(--muted)}footer{font-size:12px;color:var(--muted);padding:25px 0}.hidden{display:none}.pager{display:flex;justify-content:space-between;align-items:center;margin-top:20px}
@media(max-width:700px){header{padding:24px 18px}h1{font-size:28px}main{padding:14px}.stats{grid-template-columns:repeat(2,1fr);gap:8px}.stat{padding:12px}.stat b{font-size:22px}article,.panel{padding:15px}.rowhead{align-items:start}h2{font-size:20px}.metrics{gap:15px}.changegrid{grid-template-columns:1fr}.toolbar>.search{flex:1 0 100%;min-width:0}.toolbar>div:not(.search){flex:1;min-width:140px}.toolbar select{width:100%}.facts{min-width:720px}}
</style><header><div class="eyebrow">Signalpost / Evidence workspace</div><h1>Understand the company.<br>See what supports the answer.</h1><p>Norwegian company records, checked websites and dated observations. Compare facts, inspect changes and trace every supported statement.</p></header>
<main><div id="stats" class="stats"></div><div class="toolbar"><div class="search"><label for="q">Company name or organisation number</label><input id="q" placeholder="Search companies…" autocomplete="off"></div><div><label for="filter">Show</label><select id="filter"><option value="all">All companies</option><option value="website">Verified website</option><option value="changes">With changes</option><option value="gaps">Failed or blocked sources</option></select></div><div><label for="sort">Order</label><select id="sort"><option value="name">Company name</option><option value="changes">Most changes</option><option value="coverage">Most supported fields</option></select></div><button id="comparego" class="primary" disabled>Compare selected (0)</button><button id="export">Export filtered JSONL</button></div>
<section id="comparison" class="panel hidden" aria-label="Company comparison"></section><div class="rowhead"><p id="count" aria-live="polite"></p><small>Choose up to 3 companies to compare</small></div><section id="items"></section><div class="pager"><button id="prev">Previous</button><span id="page"></span><button id="next">Next</button></div><footer id="cost"></footer><footer>Local research artifact. No official competition score. Source availability does not establish business quality. Historical filings are not live financial balances. Social links are declared on company pages; destination ownership is not independently verified.</footer></main>
<script id="data" type="application/json">DATA_PLACEHOLDER</script><script>
const rows=JSON.parse(document.getElementById('data').textContent);let page=0,selected=rows;const picks=new Set(),size=15;
const $=id=>document.getElementById(id);const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const claim=(r,k)=>r.claims.find(c=>c.field===k);const field=(r,k)=>{const c=claim(r,k);return c?.availability==='available'?c.value:null};const name=r=>field(r,'legal_name')||r.organisation_number;
const show=v=>v===null||v===undefined?'Unknown':typeof v==='object'?JSON.stringify(v,null,2):String(v);
const labels={'legal_form':'Legal form','industry':'Registered industry','employees':'Employees','financials.revenue':'Filed revenue','financials.net_income':'Filed net income','financials.equity':'Filed equity','financials.currency':'Filing currency','website.verified_url':'Verified website','website.hiring':'Hiring evidence','website.activity':'Dated activity'};const period=p=>p?`${p.fraDato||'Unknown'} to ${p.tilDato||'Unknown'}`:'';const human=c=>c.availability!=='available'?'Unknown':c.field==='industry'?`${c.value.beskrivelse||''} (${c.value.kode||''})`:typeof c.value==='number'?new Intl.NumberFormat('en-GB',{maximumFractionDigits:2}).format(c.value):show(c.value);
const support=r=>r.claims.filter(c=>c.availability==='available').length;
const gaps=r=>r.claims.some(c=>['failed','blocked'].includes(c.availability));
function evidence(r,id){let p=r;const seen=new Set();while(p&&!seen.has(p)){seen.add(p);if(p.organisation_number!==r.organisation_number)break;const e=p.evidence?.find(e=>e.id===id);if(e)return e;p=p.previous_snapshot}return null}
function source(e,compact=false){if(!e)return '';let u;try{u=new URL(e.source_url);if(!['http:','https:'].includes(u.protocol))return ''}catch{return ''}
if(compact)return `<a href="${esc(u.href)}" target="_blank" rel="noopener noreferrer" title="Retrieved ${esc(e.retrieved_at)}">${esc(u.hostname)}</a>`;
return `<div class="source"><a href="${esc(u.href)}" target="_blank" rel="noopener noreferrer">${esc(e.source_url)}</a><small>Retrieved ${esc(e.retrieved_at)} · ${esc(e.source_class)}</small><small>Content SHA256 ${esc(e.content_sha256)}</small>${e.excerpt?`<p>${esc(e.excerpt)}</p>`:''}</div>`}
function refs(r,ids,compact=false){return [...new Set(ids||[])].map(id=>source(evidence(r,id),compact)).join('')}
function cell(r,k){const c=claim(r,k);if(!c)return '<span class="unknown">Not collected</span>';return `<span class="${c.availability==='available'?'available':'unknown'}">${esc(c.availability)}</span><pre>${esc(human(c))}</pre>${c.reporting_period?`<small>Period ${esc(period(c.reporting_period))}</small>`:''}<div class="refs">${refs(r,c.evidence_ids,true)}</div>`}
function changes(r){if(!r.changes.length)return '<p class="muted">No supported changes in this observation. Missing or failed observations do not prove stability.</p>';return r.changes.map(c=>`<div class="change"><h3>${esc(c.field)}</h3><div class="changegrid"><div><small>Last supported observation</small><pre>${esc(show(c.old_value))}</pre><small>${esc(period(c.old_period))}</small>${refs(r.previous_snapshot||r,c.old_evidence_ids)}</div><div><small>Current observation</small><pre>${esc(show(c.new_value))}</pre><small>${esc(period(c.new_period))}</small>${refs(r,c.new_evidence_ids)}</div></div></div>`).join('')}
function insight(r,s){return `<div class="insight ${s.kind==='calculation'?'calc':''}"><p>${esc(s.text)}</p><div class="refs">${refs(r,s.evidence_ids||s.claim_fields.flatMap(f=>claim(r,f)?.evidence_ids||[]),true)}</div></div>`}
function compare(){const box=$('comparison');const rs=rows.filter(r=>picks.has(r.organisation_number));box.classList.toggle('hidden',!rs.length);$('comparego').disabled=!rs.length;$('comparego').textContent=`Compare selected (${rs.length})`;if(!rs.length)return;const fs=['legal_form','industry','employees','financials.revenue','financials.net_income','financials.equity','financials.currency','website.verified_url','website.hiring','website.activity'];box.innerHTML=`<div class="rowhead"><h2>Company comparison</h2><button id="clear">Clear selection</button></div><p class="muted">Compare the reporting periods and currencies in each cell. No currency conversion or automatic ranking is applied.</p><div class="scroll"><table class="comparetable"><thead><tr><th>Field</th>${rs.map(r=>`<th>${esc(name(r))}<br><small>${esc(r.organisation_number)}</small></th>`).join('')}</tr></thead><tbody>${fs.map(f=>`<tr><th>${esc(labels[f]||f)}</th>${rs.map(r=>`<td>${cell(r,f)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;$('clear').onclick=()=>{picks.clear();render()}}
function render(){const part=selected.slice(page*size,page*size+size);$('count').textContent=`${selected.length} companies · ${picks.size} selected`;$('page').textContent=`Page ${page+1} of ${Math.max(1,Math.ceil(selected.length/size))}`;
$('items').innerHTML=part.map(r=>`<article><div class="rowhead"><div><small>${esc(r.organisation_number)}</small><h2>${esc(name(r))}</h2></div><label><input type="checkbox" data-pick="${esc(r.organisation_number)}" ${picks.has(r.organisation_number)?'checked':''} ${picks.size>=3&&!picks.has(r.organisation_number)?'disabled':''}> Compare</label></div><span class="pill ${field(r,'website.verified_url')?'':'warning'}">${field(r,'website.verified_url')?'Website identity verified':'Website not established'}</span>${gaps(r)?'<span class="pill warning">Source gaps</span>':''}<div class="metrics"><span>Supported fields<b>${support(r)} / ${r.claims.length}</b></span><span>Material changes<b>${r.changes.length}</b></span><span>Observation completed<b>${esc(r.run.completed_at?.slice(0,10)||'Unknown')}</b></span></div><div class="summarytext">${(r.synthesis||[]).filter(s=>s.kind!=='limitation').map(s=>insight(r,s)).join('')}</div><details><summary>Unknowns and collection limits</summary>${(r.synthesis||[]).filter(s=>s.kind==='limitation').map(s=>`<div class="limit">${esc(s.text)}</div>`).join('')||'<p>No field limitations recorded.</p>'}<pre>${esc(JSON.stringify(r.errors,null,2))}</pre></details><details><summary>Changes with before / after evidence (${r.changes.length})</summary>${changes(r)}</details><details><summary>All facts and evidence</summary><div class="scroll"><table class="facts"><thead><tr><th>Field</th><th>Value and reporting period</th><th>Status and sources</th></tr></thead><tbody>${r.claims.map(c=>`<tr><td>${esc(c.field)}</td><td><pre>${esc(show(c.availability==='available'?c.value:null))}</pre><small>${c.reporting_period?esc(period(c.reporting_period)):''}</small></td><td><span class="${c.availability==='available'?'available':'unknown'}">${esc(c.availability)}</span>${c.source_pointer?`<p>Location: ${esc(c.source_pointer)}</p>`:''}${c.identity_support?`<details><summary>Identity match</summary><p>Registry name: ${esc(c.identity_support.registered_name)}</p><p>Registered site: ${esc(c.identity_support.registered_website)}<br>Observed destination: ${esc(c.identity_support.observed_entry_url)}</p><p>Matching text on the checked page:</p>${c.identity_support.literal_spans.map(x=>`<blockquote>${esc(x.text)}</blockquote>`).join('')}</details>`:''}${c.evidence_excerpt?`<blockquote>${esc(c.evidence_excerpt)}</blockquote>`:''}${refs(r,c.evidence_ids)}</td></tr>`).join('')}</tbody></table></div></details></article>`).join('')||'<div class="empty">No companies match these filters.</div>';
$('prev').disabled=page===0;$('next').disabled=(page+1)*size>=selected.length;document.querySelectorAll('[data-pick]').forEach(el=>el.onchange=()=>{el.checked?picks.add(el.dataset.pick):picks.delete(el.dataset.pick);render()});compare()}
function filter(){const q=$('q').value.toLocaleLowerCase(),f=$('filter').value;selected=rows.filter(r=>(r.organisation_number+' '+name(r)).toLocaleLowerCase().includes(q)&&(f==='all'||f==='website'&&field(r,'website.verified_url')||f==='changes'&&r.changes.length||f==='gaps'&&gaps(r)));const sort=$('sort').value;selected.sort((a,b)=>(sort==='changes'?b.changes.length-a.changes.length:sort==='coverage'?support(b)-support(a):0)||String(name(a)).localeCompare(String(name(b))));page=0;render()}
$('comparego').onclick=()=>$('comparison').scrollIntoView({behavior:'smooth',block:'start'});$('q').oninput=filter;$('filter').onchange=filter;$('sort').onchange=filter;$('prev').onclick=()=>{page--;render()};$('next').onclick=()=>{page++;render()};
$('export').onclick=()=>{const blob=new Blob([selected.map(r=>JSON.stringify(r)).join('\\n')+'\\n'],{type:'application/x-ndjson'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='signalpost-filtered.jsonl';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
$('stats').innerHTML=[[rows.length,'Company profiles'],[rows.filter(r=>field(r,'website.verified_url')).length,'Verified company websites'],[rows.filter(gaps).length,'Profiles with failed / blocked sources'],[rows.filter(r=>r.changes.length).length,'Profiles with observed changes']].map(([n,l])=>`<div class="stat"><b>${n}</b><span>${l}</span></div>`).join('');
const apiCost=rows.some(r=>r.operations.third_party_cost_usd===null)?'API charge not reconciled':`$${rows.reduce((n,r)=>n+(r.operations.third_party_cost_usd||0),0)} recorded API charge`;$('cost').textContent=`This artifact: ${rows.reduce((n,r)=>n+r.operations.requests,0)} new requests · ${rows.reduce((n,r)=>n+r.operations.cache_hits,0)} cached responses reused · ${apiCost}. Development and equipment costs excluded.`;filter();
</script></html>'''


def build(rows):
    payload = json.dumps(rows, ensure_ascii=False).replace('<', '\\u003c').replace('>', '\\u003e').replace('&', '\\u0026')
    return TEMPLATE.replace('DATA_PLACEHOLDER', payload)


def main():
    parser = argparse.ArgumentParser(); parser.add_argument('input'); parser.add_argument('output'); args = parser.parse_args()
    rows = [json.loads(line) for line in Path(args.input).read_text().splitlines() if line.strip()]
    Path(args.output).write_text(build(rows))


if __name__ == '__main__':
    main()
